name: vtime
description: An advanced, minimalist and powerful time management application.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_bloc: ^7.0.1
  logger:
  syncfusion_flutter_charts: ^19.1.69+1
  flutter_slidable: ^0.6.0
  cupertino_icons: ^1.0.2
  just_audio: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  flutter_lints: ^1.0.2
  build_runner: ^2.0.4
  hive_generator: ^1.1.0
  mockito:

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/i18n/tr.json
    - assets/i18n/ru.json
    - assets/i18n/ka.json
    - assets/alarms/alarm.mp3
